// let numberOfFaculty:number = 6;
// let numberOfManagement: number = 4;
// let totalNumberOfFaculty = 10
// console.log(totalNumberOfFaculty + numberOfManagement);
// let numberOfFaculty:number = 6;
// let numberOfManagement: number = 4;
// let totalNumberOfFaculty = 10;
// console.log(totalNumberOfFaculty - numberOfManagement);
// let totalMarks: number = 1100;
// let obtainedMarks = 899;
// let percentage = 100;
// console.log(obtainedMarks / totalMarks * percentage);
var Ali = 10;
++Ali;
++Ali;
--Ali;
++Ali;
++Ali;
--Ali;
console.log(Ali);
